services:
  db:
    image: mariadb:10.11
    container_name: dwese2526-proyecto-propio-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: proyecto_propio
      MARIADB_USER: aov
      MARIADB_PASSWORD: 2511
    ports:
      - "3307:3306"
    volumes:
      - proyecto_propio_db:/var/lib/mysql

volumes:
  proyecto_propio_db:
