spring.application.name=dwese2526-proyecto-propio-webapp-aov

# =========================
# VARIABLES DE ENTORNO (.env)
# =========================
spring.config.import=optional:file:.env[.properties]

# =========================
# SERVIDOR
# =========================
server.port=${APP_PORT:8080}

# =========================
# DATASOURCE (MariaDB)
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# =========================
# SQL INIT (MUY IMPORTANTE)
# =========================
# Usamos schema.sql + data.sql
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# POOL DE CONEXIONES
# =========================
spring.datasource.hikari.maximum-pool-size=10

# =========================
# I18N
# =========================
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# =========================
# LOGGING (ÚTIL AHORA)
# =========================
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG
