spring.application.name=dwese2526-proyecto-propio-webapp-aov

# Importa variables del archivo .env
spring.config.import=optional:file:.env[.properties]

# Puerto donde se ejecuta la aplicacion
server.port=${APP_PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# Forzar ejecucion de schema.sql y data.sql
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

# Dialecto para MariaDB
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Mostrar SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Pool de conexiones
spring.datasource.hikari.maximum-pool-size=10

spring.messages.basename=messages
spring.messages.encoding=UTF-8


logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG
